name: Docker Build and Push

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      GCR_REGISTRY:
        required: true
        type: string
        default: 'eu.gcr.io'
    secrets:
      GCR_JSON_KEY:
        required: true
        type: string

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build dockerfile
        run: echo Docker image built and pushed

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.GCR_REGISTRY }}
          username: _json_key_base64
          password: ${{ secrets.GCR_JSON_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.SERVICE_NAME }}:${{ .GITHUB_SHA }}
