name: Docker Build and Push

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      WORKING_DIR:
        required: false
        type: string
        default: "."
      GCR_REGISTRY:
        required: false
        type: string
        default: 'gcr.io'
      GCR_REGISTRY_PROJECT:
        required: true
        type: string
      PR_CHECK:
        required: false 
        type: boolean
        default: false
      GCP_AUTH:
        required: false 
        type: boolean
        default: false
      WORKLOAD_IDENTITY_PROVIDER:
        type: string
        required: false
      WIP_SERVICE_ACCOUNT:
        type: string
        required: false
    secrets:
      GCR_JSON_KEY:
        required: true
      APP9_LIBRARIES_KEY:
        required: true

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        if: ${{ inputs.GCP_AUTH }}
        id: auth
        uses: google-github-actions/auth@v2.1.7
        with:
          workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.WIP_SERVICE_ACCOUNT }}
          token_format: 'access_token'
          access_token_lifetime: '900s'
          create_credentials_file: true

      - name: Login to GCR
        if: ${{ inputs.PR_CHECK == false }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.GCR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Write GCP service account key to file
        run: echo "${{ secrets.APP9_LIBRARIES_KEY }}" > /tmp/app9_service_account_key.json

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.WORKING_DIR }}
          push: false
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:latest,${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}
          labels: |
            COMMIT_SHA=${{ github.sha }}
          secrets: |
            id=app9_service_account_key,src=/tmp/app9_service_account_key.json

      - name: Push Docker Image
        if: ${{ inputs.PR_CHECK == false }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.WORKING_DIR }}
          push: true
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:latest,${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}
          labels: |
            COMMIT_SHA=${{ github.sha }}

      - name: Done
        run: echo build succesfully!
