name: Java

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      javaVersion:
        required: false
        type: number
        default: 17
      javaDistribution:
        required: false
        type: string
        default: 'corretto'
      GCR_REGISTRY:
        required: true
        type: string
        default: 'eu.gcr.io'
      GCR_REGISTRY_PROJECT:
        required: true
        type: string
    secrets:
      GCR_JSON_KEY:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: ${{ inputs.javaDistribution }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew :${{ inputs.serviceName }}:build -x test

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.GCR_REGISTRY }}
          username: _json_key_base64
          password: ${{ secrets.GCR_JSON_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}

      - name: Done
        run: echo build succesfully!


