name: Java

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      JAVA_VERSION:
        required: false
        type: number
        default: 17
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: 'corretto'
      GCR_REGISTRY:
        required: false
        type: string
        default: 'gcr.io'
      GCR_REGISTRY_PROJECT:
        required: true
        type: string
    secrets:
      GCR_JSON_KEY:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew :${{ inputs.SERVICE_NAME }}:build
      
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.GCR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.SERVICE_NAME }}
          push: true
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}

      - name: Done
        run: echo build succesfully!


