name: Java

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      javaVersion:
        required: false
        type: number
        default: 17
      javaDistribution:
        required: false
        type: string
        default: 'corretto'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: ${{ inputs.javaDistribution }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew :${{ inputs.serviceName }}:build -x test

      - name: Done
        run: echo build succesfully!


