name: Nodejs

on:
  workflow_call:
    inputs:
      WORKING_DIR:
        required: false
        type: string
        default: "."
      SERVICE_NAME:
        required: true
        type: string
      RUN_TESTS:
        required: false
        type: boolean
        default: false
      NODE_VERSION:
        required: false
        type: number
        default: 22
      GCR_REGISTRY:
        required: false
        type: string
        default: "gcr.io"
      GCR_REGISTRY_PROJECT:
        required: true
        type: string
      TRIVY_SCAN_ENABLED:
        required: false
        type: boolean
        default: true
      TRIVY_TIMEOUT:
        required: false
        type: string
        default: "10m0s"
      PR_CHECK:
        required: false 
        type: boolean
        default: false
      ENVIRONMENT:
        type: string
        required: false
      GCR_WORKLOAD_IDENTITY_PROVIDER:
        type: string
        required: true
      GCR_SERVICE_ACCOUNT:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export Secrets from github
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          exclude: GCR_JSON_KEY

      - name: Export ENV vars from github
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Running Tests
        if: ${{ inputs.RUN_TESTS }}
        run: pnpm test

      - name: Build App
        id: build
        run: pnpm build

      - name: Build Docker Image
        if: ${{ inputs.PR_CHECK }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.WORKING_DIR }}
          push: false
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:latest,${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}
          labels: |
            COMMIT_SHA=${{ github.sha }}
            
        # v0.2.6
      - name: Setup Trivy
        if: ${{ inputs.PR_CHECK && inputs.TRIVY_SCAN_ENABLED }}
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514

      - name: Trivy vulnerability scanner
        if: ${{ inputs.PR_CHECK && inputs.TRIVY_SCAN_ENABLED }}
        run: |
          trivy image \
            --format table \
            --exit-code 1 \
            --security-checks vuln \
            --vuln-type library \
            --severity CRITICAL \
            --timeout "${{ inputs.TRIVY_TIMEOUT }}" \
            "${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}"

      - name: Authenticate with Google Cloud Registry
        if: ${{ !inputs.PR_CHECK }}
        id: auth-gcr
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ inputs.GCR_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.GCR_SERVICE_ACCOUNT }}
          token_format: 'access_token'
          access_token_lifetime: '900s'

      - name: Login to Artifact Registry
        if: ${{ !inputs.PR_CHECK }}
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.GCR_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth-gcr.outputs.access_token }}

      - name: Build and Push Docker Image
        if: ${{ !inputs.PR_CHECK }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.WORKING_DIR }}
          push: true
          tags: ${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:latest,${{ inputs.GCR_REGISTRY }}/${{ inputs.GCR_REGISTRY_PROJECT }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}
          labels: |
            COMMIT_SHA=${{ github.sha }}
