name: Java17-Corretto

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: gradlew :${{ inputs.serviceName }}:build -x test

      - name: Done
        run: echo built succesfully!


